version: '2'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/public
       
  pearlbee:
    build: pearlbee
    #volumes:
      #- 
    #ports:
     # - "5000:5000"
    command: carton exec  starman   bin/app.psgi 
    environment:
      - MYSQL_PASSWORD=secret
            
    depends_on:
      - mysql  
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=root    
